import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "@/lib/fonts";

import { ThemeProvider } from "@/components/theme-color/theme-provider"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <ThemeProvider 
          attribute="class"
          defaultTheme="dark"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
